---
consumer key: '6t1TegHgZM01spIJnsLjZtIHM6c7qR5BzHHGuAKfMz4ecIzenK'
consumer secret: 'ELhQmF3M6ZNsCYp0eKw49iNfOcVVXvcp7Vu5GV71hvDJVQiJNJ'
oauth token: 'wfXWoOFX66FQDsY3SMmdrsX2pZEQW3cPLHlNNU3Mb48sHrsV65'
oauth secret: 'YgvcRM1y1UwI8oZwCyhS0NRNbURaIdf5UUaOpS7gZcwPAaPNQj'
wp url: 'ijustwantfreedom.com'
username: 'mxb'
password: 'H@l0b!um'
---
